import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database types
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          name: string;
          email: string;
          role: 'admin' | 'manager' | 'telemarketing-mobil' | 'telemarketing-bus' | 'telemarketing-elf' | 'telemarketing-hiace';
          is_active: boolean;
          permissions: string[];
          last_login: string | null;
          login_attempts: number;
          locked_until: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          role: 'admin' | 'manager' | 'telemarketing-mobil' | 'telemarketing-bus' | 'telemarketing-elf' | 'telemarketing-hiace';
          is_active?: boolean;
          permissions?: string[];
          last_login?: string | null;
          login_attempts?: number;
          locked_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          role?: 'admin' | 'manager' | 'telemarketing-mobil' | 'telemarketing-bus' | 'telemarketing-elf' | 'telemarketing-hiace';
          is_active?: boolean;
          permissions?: string[];
          last_login?: string | null;
          login_attempts?: number;
          locked_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          address: string;
          license_number: string;
          license_expiry: string;
          date_of_birth: string;
          loyalty_points: number;
          is_blacklisted: boolean;
          is_sales_goal: boolean;
          sales_goal_notes: string | null;
          preferred_vehicle_type: 'mobil' | 'bus' | 'elf' | 'hiace' | 'mixed';
          vehicle_history: string[];
          total_rental_days: number;
          average_rental_duration: number;
          longest_rental_duration: number;
          shortest_rental_duration: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          address: string;
          license_number: string;
          license_expiry: string;
          date_of_birth: string;
          loyalty_points?: number;
          is_blacklisted?: boolean;
          is_sales_goal?: boolean;
          sales_goal_notes?: string | null;
          preferred_vehicle_type: 'mobil' | 'bus' | 'elf' | 'hiace' | 'mixed';
          vehicle_history?: string[];
          total_rental_days?: number;
          average_rental_duration?: number;
          longest_rental_duration?: number;
          shortest_rental_duration?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          address?: string;
          license_number?: string;
          license_expiry?: string;
          date_of_birth?: string;
          loyalty_points?: number;
          is_blacklisted?: boolean;
          is_sales_goal?: boolean;
          sales_goal_notes?: string | null;
          preferred_vehicle_type?: 'mobil' | 'bus' | 'elf' | 'hiace' | 'mixed';
          vehicle_history?: string[];
          total_rental_days?: number;
          average_rental_duration?: number;
          longest_rental_duration?: number;
          shortest_rental_duration?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      vehicles: {
        Row: {
          id: string;
          make: string;
          model: string;
          year: number;
          license_plate: string;
          vin: string;
          color: string;
          fuel_type: string;
          transmission: string;
          seats: number;
          daily_rate: number;
          status: 'available' | 'rented' | 'maintenance' | 'retired';
          mileage: number;
          acquisition_cost: number;
          kir_expiry: string | null;
          tax_due: string | null;
          insurance_expiry: string | null;
          last_service: string | null;
          next_service: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          make: string;
          model: string;
          year: number;
          license_plate: string;
          vin: string;
          color: string;
          fuel_type: string;
          transmission: string;
          seats: number;
          daily_rate: number;
          status?: 'available' | 'rented' | 'maintenance' | 'retired';
          mileage?: number;
          acquisition_cost: number;
          kir_expiry?: string | null;
          tax_due?: string | null;
          insurance_expiry?: string | null;
          last_service?: string | null;
          next_service?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          make?: string;
          model?: string;
          year?: number;
          license_plate?: string;
          vin?: string;
          color?: string;
          fuel_type?: string;
          transmission?: string;
          seats?: number;
          daily_rate?: number;
          status?: 'available' | 'rented' | 'maintenance' | 'retired';
          mileage?: number;
          acquisition_cost?: number;
          kir_expiry?: string | null;
          tax_due?: string | null;
          insurance_expiry?: string | null;
          last_service?: string | null;
          next_service?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      kir_records: {
        Row: {
          id: string;
          vehicle_id: string;
          vehicle_plate: string;
          inspection_date: string;
          expiry_date: string;
          status: 'valid' | 'expired' | 'expiring-soon';
          inspector: string;
          certificate_number: string;
          cost: number;
          notes: string | null;
          document_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vehicle_id: string;
          vehicle_plate: string;
          inspection_date: string;
          expiry_date: string;
          status: 'valid' | 'expired' | 'expiring-soon';
          inspector: string;
          certificate_number: string;
          cost?: number;
          notes?: string | null;
          document_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vehicle_id?: string;
          vehicle_plate?: string;
          inspection_date?: string;
          expiry_date?: string;
          status?: 'valid' | 'expired' | 'expiring-soon';
          inspector?: string;
          certificate_number?: string;
          cost?: number;
          notes?: string | null;
          document_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tax_records: {
        Row: {
          id: string;
          vehicle_id: string;
          vehicle_plate: string;
          tax_type: 'annual' | 'transfer' | 'penalty';
          tax_year: number;
          base_amount: number;
          has_tax: boolean;
          tax_rate: number;
          tax_amount: number;
          total_amount: number;
          due_date: string;
          paid_date: string | null;
          status: 'pending' | 'paid' | 'overdue';
          description: string | null;
          document_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vehicle_id: string;
          vehicle_plate: string;
          tax_type: 'annual' | 'transfer' | 'penalty';
          tax_year: number;
          base_amount: number;
          has_tax?: boolean;
          tax_rate?: number;
          tax_amount?: number;
          total_amount: number;
          due_date: string;
          paid_date?: string | null;
          status?: 'pending' | 'paid' | 'overdue';
          description?: string | null;
          document_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vehicle_id?: string;
          vehicle_plate?: string;
          tax_type?: 'annual' | 'transfer' | 'penalty';
          tax_year?: number;
          base_amount?: number;
          has_tax?: boolean;
          tax_rate?: number;
          tax_amount?: number;
          total_amount?: number;
          due_date?: string;
          paid_date?: string | null;
          status?: 'pending' | 'paid' | 'overdue';
          description?: string | null;
          document_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      maintenance_records: {
        Row: {
          id: string;
          vehicle_id: string;
          vehicle_plate: string;
          type: 'scheduled' | 'repair' | 'inspection';
          description: string;
          scheduled_date: string;
          completed_date: string | null;
          status: 'pending' | 'in-progress' | 'completed' | 'overdue';
          cost: number;
          technician: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vehicle_id: string;
          vehicle_plate: string;
          type: 'scheduled' | 'repair' | 'inspection';
          description: string;
          scheduled_date: string;
          completed_date?: string | null;
          status?: 'pending' | 'in-progress' | 'completed' | 'overdue';
          cost?: number;
          technician?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vehicle_id?: string;
          vehicle_plate?: string;
          type?: 'scheduled' | 'repair' | 'inspection';
          description?: string;
          scheduled_date?: string;
          completed_date?: string | null;
          status?: 'pending' | 'in-progress' | 'completed' | 'overdue';
          cost?: number;
          technician?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      vendors: {
        Row: {
          id: string;
          name: string;
          vehicle_type: 'mobil' | 'bus' | 'elf' | 'hiace';
          category: string;
          contact: string;
          email: string;
          phone: string;
          address: string;
          rating: number;
          services: string[];
          total_orders: number;
          total_spent: number;
          is_active: boolean;
          specialization: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          vehicle_type: 'mobil' | 'bus' | 'elf' | 'hiace';
          category: string;
          contact: string;
          email: string;
          phone: string;
          address: string;
          rating?: number;
          services?: string[];
          total_orders?: number;
          total_spent?: number;
          is_active?: boolean;
          specialization?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          vehicle_type?: 'mobil' | 'bus' | 'elf' | 'hiace';
          category?: string;
          contact?: string;
          email?: string;
          phone?: string;
          address?: string;
          rating?: number;
          services?: string[];
          total_orders?: number;
          total_spent?: number;
          is_active?: boolean;
          specialization?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      competitor_prices: {
        Row: {
          id: string;
          competitor: string;
          vehicle_category: string;
          daily_rate: number;
          location: string;
          date: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          competitor: string;
          vehicle_category: string;
          daily_rate: number;
          location: string;
          date: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          competitor?: string;
          vehicle_category?: string;
          daily_rate?: number;
          location?: string;
          date?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          invoice_number: string;
          customer_id: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          customer_address: string;
          issue_date: string;
          due_date: string;
          subtotal: number;
          has_tax: boolean;
          tax_rate: number;
          tax_amount: number;
          total: number;
          status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
          notes: string | null;
          total_rental_days: number;
          average_daily_rate: number;
          duration_discount: number;
          duration_discount_percentage: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          invoice_number: string;
          customer_id: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          customer_address: string;
          issue_date: string;
          due_date: string;
          subtotal: number;
          has_tax?: boolean;
          tax_rate?: number;
          tax_amount?: number;
          total: number;
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
          notes?: string | null;
          total_rental_days?: number;
          average_daily_rate?: number;
          duration_discount?: number;
          duration_discount_percentage?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          invoice_number?: string;
          customer_id?: string;
          customer_name?: string;
          customer_email?: string;
          customer_phone?: string;
          customer_address?: string;
          issue_date?: string;
          due_date?: string;
          subtotal?: number;
          has_tax?: boolean;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
          notes?: string | null;
          total_rental_days?: number;
          average_daily_rate?: number;
          duration_discount?: number;
          duration_discount_percentage?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          total: number;
          vehicle_id: string | null;
          rental_days: number | null;
          start_date: string | null;
          end_date: string | null;
          duration_category: 'short' | 'medium' | 'long' | 'extended' | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          description: string;
          quantity?: number;
          unit_price: number;
          total: number;
          vehicle_id?: string | null;
          rental_days?: number | null;
          start_date?: string | null;
          end_date?: string | null;
          duration_category?: 'short' | 'medium' | 'long' | 'extended' | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          description?: string;
          quantity?: number;
          unit_price?: number;
          total?: number;
          vehicle_id?: string | null;
          rental_days?: number | null;
          start_date?: string | null;
          end_date?: string | null;
          duration_category?: 'short' | 'medium' | 'long' | 'extended' | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      hpp_calculations: {
        Row: {
          id: string;
          vehicle_id: string;
          period: string;
          acquisition_cost: number;
          maintenance_costs: number;
          insurance_costs: number;
          tax_costs: number;
          fuel_costs: number;
          depreciation_costs: number;
          operating_costs: number;
          total_costs: number;
          revenue: number;
          profit: number;
          profit_margin: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vehicle_id: string;
          period: string;
          acquisition_cost: number;
          maintenance_costs?: number;
          insurance_costs?: number;
          tax_costs?: number;
          fuel_costs?: number;
          depreciation_costs?: number;
          operating_costs?: number;
          total_costs: number;
          revenue: number;
          profit: number;
          profit_margin: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vehicle_id?: string;
          period?: string;
          acquisition_cost?: number;
          maintenance_costs?: number;
          insurance_costs?: number;
          tax_costs?: number;
          fuel_costs?: number;
          depreciation_costs?: number;
          operating_costs?: number;
          total_costs?: number;
          revenue?: number;
          profit?: number;
          profit_margin?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}